### ISSUE TITLE
Generate a ReadMe for this repo

### ISSUE THREAD

**Issue by procheta1999** [procheta1999/dayofcode5#3]
Generate a proper ReadMe for this repo following markdown conditions and syntax.
Necessary thing to be included:
1) An introduction
2) Tech stack used with icons
3) A short description of the project

**Comment by Sajal193** [comment]
Hi procheta1999. I'd like to contribute to this issue as a part of ongoing hacktoberfest 2021

**Comment by procheta1999** [comment]
Ok . You are assigned.

**Comment by Sajal193** [comment]
Thanks! Can I add desccription of each image in the readme file like the information and others...?

**Comment by procheta1999** [comment]
not needed

**Comment by pranjal-arora** [comment]
Hey! I'd like to take up this issue, if not resolved. Please do make me an assignee.

**Comment by procheta1999** [comment]
@Sajal193 has already been assigned. @pranjal-arora  If I open any other issue in any of my repos, feel free to contribute :)

**Comment by Sajal193** [comment]
I have created a new readme file considering markdown conditions and syntax
However I'm facing issues in creating a pull request. I'll get back to it in few minutes.

**Comment by Sajal193** [comment]
Hi @procheta1999, I've created a pull request. Kindly go through it and give your suggestions. Thank you
